version: "3.9"
services:
  app:
    build: .
    image: connectfour-app:latest
    container_name: connectfour
    ports:
      - "8502:8502"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./:/app:rw
    command: ["streamlit", "run", "src/app/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8502"]
